# fly.toml app configuration file generated for custom-rom-index on 2025-01-02T16:17:50+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'custom-rom-index'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
NODE_OPTIONS = "--max-old-space-size=256"
