name: Cron

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm i -g corepack@latest && corepack enable
      - run: pnpm i --frozen-lockfile
      - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}; npm run sync; node scripts/fill-release-dates.js;
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":robot: Sync Services!"
          branch: ${{ github.head_ref }}
